# Generated by Django 5.0.7 on 2024-08-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projeto", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projeto",
            name="deadline",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="finished_at",
            field=models.DateField(null=True),
        ),
    ]
